package pt.uminho.sysbio.biosynth.integration.etl;

public enum MetaboliteQualityLabel {
	
	//Formula Labels
	FORMULA_EXACT, FORMULA_EMPTY, FORMULA_MISMATCH, FORMULA_MISMATCH_HYDROGEN,
	
	//InChI Labels
	INCHI_MISMATCH, INCHI_SECOND_HASH_BLOCK_MISMATCH, INCHI_P_BLOCK_MISMATCH, 
	INCHI_VERSION_MISMATCH, INCHI_VERSION_1, INCHI_VERSION_2, 
	INCHI_STANDARD, INCHI_NON_STANDARD, INCHI_MIXED_F,
	
	//SMILES TOO CONFUSING !
	SMILES_MISMATCH, 
	
	
	CHARGE_MISMATCH, 
	CROSSREFERENCE_EXTERNAL, CROSSREFERENCE_EXTERNAL_OUT, 
	MULTIPLE_DATABASES, 
}
