package pt.uminho.sysbio.biosynth.integration.etl;

public enum MetaboliteQualityLabel {
	EXACT_FORMULA, NO_FORMULA, FORMULA_MISMATCH, FORMULA_MISMATCH_HYDROGEN,
	INCHI_MISMATCH, INCHI_SECOND_HASH_BLOCK_MISMATCH, INCHI_P_BLOCK_MISMATCH, 
	INCHI_VERSION_MISMATCH, INCHI_VERSION_1, INCHI_VERSION_2, 
	INCHI_STANDARD, INCHI_NON_STANDARD, INCHI_MIXED_F,
	
	SMILES_MISMATCH, 
	CHARGE_MISMATCH, 
	EXTERNAL_CROSSREFERENCE, 
	MULTIPLE_DATABASES, 
}
