package pt.uminho.sysbio.biosynth.integration.etl;

public enum MetaboliteQualityLabel {
	EXACT_FORMULA, NO_FORMULA, FORMULA_MISMATCH, FORMULA_MISMATCH_HYDROGEN,
	INCHI_MISMATCH, 
	SMILES_MISMATCH, 
	CHARGE_MISMATCH, 
	EXTERNAL_CROSSREFERENCE, 
	MULTIPLE_DATABASES, 
}
