package edu.uminho.biosynth.core.data.integration.etl.staging.components;

// Generated 14-Feb-2014 20:21:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetaboliteNameDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_name_dim")
public class MetaboliteNameDim implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean iupac;
	private Set<MetaboliteNameBridge> metaboliteNameBridges = new HashSet<MetaboliteNameBridge>(
			0);

	public MetaboliteNameDim() {
	}

	public MetaboliteNameDim(int id) {
		this.id = id;
	}

	public MetaboliteNameDim(int id, String name, Boolean iupac,
			Set<MetaboliteNameBridge> metaboliteNameBridges) {
		this.id = id;
		this.name = name;
		this.iupac = iupac;
		this.metaboliteNameBridges = metaboliteNameBridges;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 65534)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iupac")
	public Boolean getIupac() {
		return this.iupac;
	}

	public void setIupac(Boolean iupac) {
		this.iupac = iupac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteNameDim")
	public Set<MetaboliteNameBridge> getMetaboliteNameBridges() {
		return this.metaboliteNameBridges;
	}

	public void setMetaboliteNameBridges(
			Set<MetaboliteNameBridge> metaboliteNameBridges) {
		this.metaboliteNameBridges = metaboliteNameBridges;
	}

}
