package edu.uminho.biosynth.core.data.integration.etl.staging.components;

// Generated 14-Feb-2014 20:21:31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MetaboliteNameBridgeId generated by hbm2java
 */
@Embeddable
public class MetaboliteNameBridgeId implements java.io.Serializable {

	private int nameId;
	private int nameGroupId;

	public MetaboliteNameBridgeId() {
	}

	public MetaboliteNameBridgeId(int nameId, int nameGroupId) {
		this.nameId = nameId;
		this.nameGroupId = nameGroupId;
	}

	@Column(name = "name_id", nullable = false)
	public int getNameId() {
		return this.nameId;
	}

	public void setNameId(int nameId) {
		this.nameId = nameId;
	}

	@Column(name = "name_group_id", nullable = false)
	public int getNameGroupId() {
		return this.nameGroupId;
	}

	public void setNameGroupId(int nameGroupId) {
		this.nameGroupId = nameGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MetaboliteNameBridgeId))
			return false;
		MetaboliteNameBridgeId castOther = (MetaboliteNameBridgeId) other;

		return (this.getNameId() == castOther.getNameId())
				&& (this.getNameGroupId() == castOther.getNameGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNameId();
		result = 37 * result + this.getNameGroupId();
		return result;
	}

}
