package edu.uminho.biosynth.core.data.integration.staging.components;

// Generated 12-Feb-2014 16:59:46 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetaboliteXrefGroup generated by hbm2java
 */
@Entity
@Table(name = "metabolite_xref_group")
public class MetaboliteXrefGroup implements java.io.Serializable {

	private int id;
	private MetaboliteXrefDim metaboliteXrefDim;
	private String type;
	private Set<MetaboliteStga> metaboliteStgas = new HashSet<MetaboliteStga>(0);

	public MetaboliteXrefGroup() {
	}

	public MetaboliteXrefGroup(int id, MetaboliteXrefDim metaboliteXrefDim) {
		this.id = id;
		this.metaboliteXrefDim = metaboliteXrefDim;
	}

	public MetaboliteXrefGroup(int id, MetaboliteXrefDim metaboliteXrefDim,
			String type, Set<MetaboliteStga> metaboliteStgas) {
		this.id = id;
		this.metaboliteXrefDim = metaboliteXrefDim;
		this.type = type;
		this.metaboliteStgas = metaboliteStgas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xref_id", nullable = false)
	public MetaboliteXrefDim getMetaboliteXrefDim() {
		return this.metaboliteXrefDim;
	}

	public void setMetaboliteXrefDim(MetaboliteXrefDim metaboliteXrefDim) {
		this.metaboliteXrefDim = metaboliteXrefDim;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteXrefGroup")
	public Set<MetaboliteStga> getMetaboliteStgas() {
		return this.metaboliteStgas;
	}

	public void setMetaboliteStgas(Set<MetaboliteStga> metaboliteStgas) {
		this.metaboliteStgas = metaboliteStgas;
	}

}
