package edu.uminho.biosynth.core.data.integration.staging.components;

// Generated 12-Feb-2014 16:59:46 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetaboliteNameDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_name_dim")
public class MetaboliteNameDim implements java.io.Serializable {

	private int id;
	private String name;
	private Set<MetaboliteNameGroup> metaboliteNameGroups = new HashSet<MetaboliteNameGroup>(
			0);

	public MetaboliteNameDim() {
	}

	public MetaboliteNameDim(int id) {
		this.id = id;
	}

	public MetaboliteNameDim(int id, String name,
			Set<MetaboliteNameGroup> metaboliteNameGroups) {
		this.id = id;
		this.name = name;
		this.metaboliteNameGroups = metaboliteNameGroups;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 2048)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteNameDim")
	public Set<MetaboliteNameGroup> getMetaboliteNameGroups() {
		return this.metaboliteNameGroups;
	}

	public void setMetaboliteNameGroups(
			Set<MetaboliteNameGroup> metaboliteNameGroups) {
		this.metaboliteNameGroups = metaboliteNameGroups;
	}

}
