package edu.uminho.biosynth.core.data.integration.staging.components;

// Generated 12-Feb-2014 16:59:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MetaboliteStga generated by hbm2java
 */
@Entity
@Table(name = "metabolite_stga")
public class MetaboliteStga implements java.io.Serializable {

	private static final long serialVersionUID = -588617301617248103L;
	
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	private int id;
	private MetaboliteXrefGroup metaboliteXrefGroup;
	private MetaboliteNameGroup metaboliteNameGroup;
	private MetaboliteInchiDim metaboliteInchiDim;
	private MetaboliteSmilesDim metaboliteSmilesDim;
	private MetaboliteFormulaDim metaboliteFormulaDim;
	private MetaboliteServiceDim metaboliteServiceDim;
	private Integer numeryKey;
	private String textKey;
	private String comment;
	private String remark;
	private String description;
	private String formula;
	private String class_;

	public MetaboliteStga() {
	}

	public MetaboliteStga(int id) {
		this.id = id;
	}

	public MetaboliteStga(int id, MetaboliteXrefGroup metaboliteXrefGroup,
			MetaboliteNameGroup metaboliteNameGroup,
			MetaboliteInchiDim metaboliteInchiDim,
			MetaboliteSmilesDim metaboliteSmilesDim,
			MetaboliteFormulaDim metaboliteFormulaDim,
			MetaboliteServiceDim metaboliteServiceDim, Integer numeryKey,
			String textKey, String comment, String remark, String description,
			String formula, String class_) {
		this.id = id;
		this.metaboliteXrefGroup = metaboliteXrefGroup;
		this.metaboliteNameGroup = metaboliteNameGroup;
		this.metaboliteInchiDim = metaboliteInchiDim;
		this.metaboliteSmilesDim = metaboliteSmilesDim;
		this.metaboliteFormulaDim = metaboliteFormulaDim;
		this.metaboliteServiceDim = metaboliteServiceDim;
		this.numeryKey = numeryKey;
		this.textKey = textKey;
		this.comment = comment;
		this.remark = remark;
		this.description = description;
		this.formula = formula;
		this.class_ = class_;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xref_group_id")
	public MetaboliteXrefGroup getMetaboliteXrefGroup() {
		return this.metaboliteXrefGroup;
	}

	public void setMetaboliteXrefGroup(MetaboliteXrefGroup metaboliteXrefGroup) {
		this.metaboliteXrefGroup = metaboliteXrefGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_group_id")
	public MetaboliteNameGroup getMetaboliteNameGroup() {
		return this.metaboliteNameGroup;
	}

	public void setMetaboliteNameGroup(MetaboliteNameGroup metaboliteNameGroup) {
		this.metaboliteNameGroup = metaboliteNameGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inchi_id")
	public MetaboliteInchiDim getMetaboliteInchiDim() {
		return this.metaboliteInchiDim;
	}

	public void setMetaboliteInchiDim(MetaboliteInchiDim metaboliteInchiDim) {
		this.metaboliteInchiDim = metaboliteInchiDim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "smiles_id")
	public MetaboliteSmilesDim getMetaboliteSmilesDim() {
		return this.metaboliteSmilesDim;
	}

	public void setMetaboliteSmilesDim(MetaboliteSmilesDim metaboliteSmilesDim) {
		this.metaboliteSmilesDim = metaboliteSmilesDim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formula_id")
	public MetaboliteFormulaDim getMetaboliteFormulaDim() {
		return this.metaboliteFormulaDim;
	}

	public void setMetaboliteFormulaDim(
			MetaboliteFormulaDim metaboliteFormulaDim) {
		this.metaboliteFormulaDim = metaboliteFormulaDim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id")
	public MetaboliteServiceDim getMetaboliteServiceDim() {
		return this.metaboliteServiceDim;
	}

	public void setMetaboliteServiceDim(
			MetaboliteServiceDim metaboliteServiceDim) {
		this.metaboliteServiceDim = metaboliteServiceDim;
	}

	@Column(name = "numery_key")
	public Integer getNumeryKey() {
		return this.numeryKey;
	}

	public void setNumeryKey(Integer numeryKey) {
		this.numeryKey = numeryKey;
	}

	@Column(name = "text_key")
	public String getTextKey() {
		return this.textKey;
	}

	public void setTextKey(String textKey) {
		this.textKey = textKey;
	}

	@Column(name = "comment", length = 16384)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "remark", length = 16384)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "description", length = 16384)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "formula")
	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	@Column(name = "class")
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
