package edu.uminho.biosynth.core.data.integration.staging.components;

// Generated 14-Feb-2014 20:21:31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MetaboliteSmilesDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_smiles_dim", uniqueConstraints = @UniqueConstraint(columnNames = "smiles"))
public class MetaboliteSmilesDim implements java.io.Serializable {

	private int id;
	private String smiles;
	private Set<MetaboliteStga> metaboliteStgas = new HashSet<MetaboliteStga>(0);

	public MetaboliteSmilesDim() {
	}

	public MetaboliteSmilesDim(int id) {
		this.id = id;
	}

	public MetaboliteSmilesDim(int id, String smiles,
			Set<MetaboliteStga> metaboliteStgas) {
		this.id = id;
		this.smiles = smiles;
		this.metaboliteStgas = metaboliteStgas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "smiles", unique = true, length = 65534)
	public String getSmiles() {
		return this.smiles;
	}

	public void setSmiles(String smiles) {
		this.smiles = smiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteSmilesDim")
	public Set<MetaboliteStga> getMetaboliteStgas() {
		return this.metaboliteStgas;
	}

	public void setMetaboliteStgas(Set<MetaboliteStga> metaboliteStgas) {
		this.metaboliteStgas = metaboliteStgas;
	}

}
