package edu.uminho.biosynth.core.data.integration.staging.components;

// Generated 12-Feb-2014 16:59:46 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetaboliteNameGroup generated by hbm2java
 */
@Entity
@Table(name = "metabolite_name_group")
public class MetaboliteNameGroup implements java.io.Serializable {

	private int id;
	private MetaboliteNameDim metaboliteNameDim;
	private Set<MetaboliteStga> metaboliteStgas = new HashSet<MetaboliteStga>(0);

	public MetaboliteNameGroup() {
	}

	public MetaboliteNameGroup(int id) {
		this.id = id;
	}

	public MetaboliteNameGroup(int id, MetaboliteNameDim metaboliteNameDim,
			Set<MetaboliteStga> metaboliteStgas) {
		this.id = id;
		this.metaboliteNameDim = metaboliteNameDim;
		this.metaboliteStgas = metaboliteStgas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_id")
	public MetaboliteNameDim getMetaboliteNameDim() {
		return this.metaboliteNameDim;
	}

	public void setMetaboliteNameDim(MetaboliteNameDim metaboliteNameDim) {
		this.metaboliteNameDim = metaboliteNameDim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteNameGroup")
	public Set<MetaboliteStga> getMetaboliteStgas() {
		return this.metaboliteStgas;
	}

	public void setMetaboliteStgas(Set<MetaboliteStga> metaboliteStgas) {
		this.metaboliteStgas = metaboliteStgas;
	}

}
