package pt.uminho.sysbio.biosynthframework.sbml;

public enum MessageCategory {
  NULL,
  FIX,
  
  OBJECT_MISSING_ID,
  
  MODEL_MISSING_ID,
  SPECIE_MISSING_ID,
  SPECIE_MISSING_COMPARMENT_ID,
  UNDECLARED_COMPARTMENT,
  
  REACTION_MISSING_ID,
  
  COMPARMENT_MISSING_ID,
  NON_NUMERIC_BOUND,
  UNDECLARED_SPECIE,
  
  STOICH_INVALID_VALUE,
  STOICH_NO_VALUE,
  STOICH_NO_SPECIES,
  STOICH_DUP_SPECIES,
  
  SPECIE_DUPLICATE_ID,
  REACTION_ID_DUPLICATE,
  COMPARTMENT_DUPLICATE_ID,
}
