package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MetaboliteNameBridge generated by hbm2java
 */
@Entity
@Table(name = "metabolite_name_bridge")
public class MetaboliteNameBridge implements java.io.Serializable {

	private MetaboliteNameBridgeId id;
	private MetaboliteNameDim metaboliteNameDim;
	private MetaboliteNameGroupDim metaboliteNameGroupDim;

	public MetaboliteNameBridge() {
	}

	public MetaboliteNameBridge(MetaboliteNameBridgeId id,
			MetaboliteNameDim metaboliteNameDim,
			MetaboliteNameGroupDim metaboliteNameGroupDim) {
		this.id = id;
		this.metaboliteNameDim = metaboliteNameDim;
		this.metaboliteNameGroupDim = metaboliteNameGroupDim;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nameId", column = @Column(name = "name_id", nullable = false)),
			@AttributeOverride(name = "nameGroupId", column = @Column(name = "name_group_id", nullable = false)) })
	public MetaboliteNameBridgeId getId() {
		return this.id;
	}

	public void setId(MetaboliteNameBridgeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_id", nullable = false, insertable = false, updatable = false)
	public MetaboliteNameDim getMetaboliteNameDim() {
		return this.metaboliteNameDim;
	}

	public void setMetaboliteNameDim(MetaboliteNameDim metaboliteNameDim) {
		this.metaboliteNameDim = metaboliteNameDim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_group_id", nullable = false, insertable = false, updatable = false)
	public MetaboliteNameGroupDim getMetaboliteNameGroupDim() {
		return this.metaboliteNameGroupDim;
	}

	public void setMetaboliteNameGroupDim(
			MetaboliteNameGroupDim metaboliteNameGroupDim) {
		this.metaboliteNameGroupDim = metaboliteNameGroupDim;
	}

}
