package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MetaboliteNameGroupDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_name_group_dim")
public class MetaboliteNameGroupDim implements java.io.Serializable {

	private int id;
	private Set<MetaboliteFact> metaboliteFacts = new HashSet<MetaboliteFact>(0);
	private Set<MetaboliteNameBridge> metaboliteNameBridges = new HashSet<MetaboliteNameBridge>(
			0);

	public MetaboliteNameGroupDim() {
	}

	public MetaboliteNameGroupDim(int id) {
		this.id = id;
	}

	public MetaboliteNameGroupDim(int id, Set<MetaboliteFact> metaboliteFacts,
			Set<MetaboliteNameBridge> metaboliteNameBridges) {
		this.id = id;
		this.metaboliteFacts = metaboliteFacts;
		this.metaboliteNameBridges = metaboliteNameBridges;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteNameGroupDim")
	public Set<MetaboliteFact> getMetaboliteFacts() {
		return this.metaboliteFacts;
	}

	public void setMetaboliteFacts(Set<MetaboliteFact> metaboliteFacts) {
		this.metaboliteFacts = metaboliteFacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteNameGroupDim")
	public Set<MetaboliteNameBridge> getMetaboliteNameBridges() {
		return this.metaboliteNameBridges;
	}

	public void setMetaboliteNameBridges(
			Set<MetaboliteNameBridge> metaboliteNameBridges) {
		this.metaboliteNameBridges = metaboliteNameBridges;
	}

}
