package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MetaboliteSmilesDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_smiles_dim", uniqueConstraints = @UniqueConstraint(columnNames = "smiles"))
public class MetaboliteSmilesDim implements java.io.Serializable {

	private int id;
	private String smiles;
	private Set<MetaboliteFact> metaboliteFacts = new HashSet<MetaboliteFact>(0);

	public MetaboliteSmilesDim() {
	}

	public MetaboliteSmilesDim(int id) {
		this.id = id;
	}

	public MetaboliteSmilesDim(int id, String smiles,
			Set<MetaboliteFact> metaboliteFacts) {
		this.id = id;
		this.smiles = smiles;
		this.metaboliteFacts = metaboliteFacts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "smiles", unique = true, length = 65534)
	public String getSmiles() {
		return this.smiles;
	}

	public void setSmiles(String smiles) {
		this.smiles = smiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteSmilesDim")
	public Set<MetaboliteFact> getMetaboliteFacts() {
		return this.metaboliteFacts;
	}

	public void setMetaboliteFacts(Set<MetaboliteFact> metaboliteFacts) {
		this.metaboliteFacts = metaboliteFacts;
	}

}
