package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MetaboliteInchiDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_inchi_dim", uniqueConstraints = @UniqueConstraint(columnNames = "inchi_key"))
public class MetaboliteInchiDim implements java.io.Serializable {

	private int id;
	private String version;
	private String inchi;
	private String inchiCharge;
	private Boolean standard;
	private String inchiKey;
	private Set<MetaboliteFact> metaboliteFacts = new HashSet<MetaboliteFact>(0);

	public MetaboliteInchiDim() {
	}

	public MetaboliteInchiDim(int id) {
		this.id = id;
	}

	public MetaboliteInchiDim(int id, String inchi, String inchiCharge,
			Boolean standard, String inchiKey,
			Set<MetaboliteFact> metaboliteFacts) {
		this.id = id;
		this.inchi = inchi;
		this.inchiCharge = inchiCharge;
		this.standard = standard;
		this.inchiKey = inchiKey;
		this.metaboliteFacts = metaboliteFacts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "inchi", length = 65534)
	public String getInchi() {
		return this.inchi;
	}

	public void setInchi(String inchi) {
		this.inchi = inchi;
	}

	@Column(name = "inchi_charge", length = 10)
	public String getInchiCharge() {
		return this.inchiCharge;
	}

	public void setInchiCharge(String inchiCharge) {
		this.inchiCharge = inchiCharge;
	}

	@Column(name = "standard")
	public Boolean getStandard() {
		return this.standard;
	}

	public void setStandard(Boolean standard) {
		this.standard = standard;
	}

	@Column(name = "inchi_key", unique = true, length = 27)
	public String getInchiKey() {
		return this.inchiKey;
	}

	public void setInchiKey(String inchiKey) {
		this.inchiKey = inchiKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteInchiDim")
	public Set<MetaboliteFact> getMetaboliteFacts() {
		return this.metaboliteFacts;
	}

	public void setMetaboliteFacts(Set<MetaboliteFact> metaboliteFacts) {
		this.metaboliteFacts = metaboliteFacts;
	}

}
