package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MetaboliteFormulaDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_formula_dim", uniqueConstraints = @UniqueConstraint(columnNames = "formula"))
public class MetaboliteFormulaDim implements java.io.Serializable {

	private int id;
	private String formula;
	private Integer carbon;
	private Integer hydrogen;
	private Integer oxygen;
	private Integer phosphorus;
	private Integer sulfur;
	private Integer chlorine;
	private Integer iron;
	private Integer calcium;
	private Integer sodium;
	private Integer nitrogen;
	private Set<MetaboliteFact> metaboliteFacts = new HashSet<MetaboliteFact>(0);

	public MetaboliteFormulaDim() {
	}

	public MetaboliteFormulaDim(int id) {
		this.id = id;
	}

	public MetaboliteFormulaDim(int id, String formula, Integer carbon,
			Integer hydrogen, Integer oxygen, Integer phosphorus,
			Integer sulfur, Integer chlorine, Integer iron, Integer calcium,
			Integer sodium, Integer nitrogen,
			Set<MetaboliteFact> metaboliteFacts) {
		this.id = id;
		this.formula = formula;
		this.carbon = carbon;
		this.hydrogen = hydrogen;
		this.oxygen = oxygen;
		this.phosphorus = phosphorus;
		this.sulfur = sulfur;
		this.chlorine = chlorine;
		this.iron = iron;
		this.calcium = calcium;
		this.sodium = sodium;
		this.nitrogen = nitrogen;
		this.metaboliteFacts = metaboliteFacts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "formula", unique = true)
	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	@Column(name = "carbon")
	public Integer getCarbon() {
		return this.carbon;
	}

	public void setCarbon(Integer carbon) {
		this.carbon = carbon;
	}

	@Column(name = "hydrogen")
	public Integer getHydrogen() {
		return this.hydrogen;
	}

	public void setHydrogen(Integer hydrogen) {
		this.hydrogen = hydrogen;
	}

	@Column(name = "oxygen")
	public Integer getOxygen() {
		return this.oxygen;
	}

	public void setOxygen(Integer oxygen) {
		this.oxygen = oxygen;
	}

	@Column(name = "phosphorus")
	public Integer getPhosphorus() {
		return this.phosphorus;
	}

	public void setPhosphorus(Integer phosphorus) {
		this.phosphorus = phosphorus;
	}

	@Column(name = "sulfur")
	public Integer getSulfur() {
		return this.sulfur;
	}

	public void setSulfur(Integer sulfur) {
		this.sulfur = sulfur;
	}

	@Column(name = "chlorine")
	public Integer getChlorine() {
		return this.chlorine;
	}

	public void setChlorine(Integer chlorine) {
		this.chlorine = chlorine;
	}

	@Column(name = "iron")
	public Integer getIron() {
		return this.iron;
	}

	public void setIron(Integer iron) {
		this.iron = iron;
	}

	@Column(name = "calcium")
	public Integer getCalcium() {
		return this.calcium;
	}

	public void setCalcium(Integer calcium) {
		this.calcium = calcium;
	}

	@Column(name = "sodium")
	public Integer getSodium() {
		return this.sodium;
	}

	public void setSodium(Integer sodium) {
		this.sodium = sodium;
	}

	@Column(name = "nitrogen")
	public Integer getNitrogen() {
		return this.nitrogen;
	}

	public void setNitrogen(Integer nitrogen) {
		this.nitrogen = nitrogen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteFormulaDim")
	public Set<MetaboliteFact> getMetaboliteFacts() {
		return this.metaboliteFacts;
	}

	public void setMetaboliteFacts(Set<MetaboliteFact> metaboliteFacts) {
		this.metaboliteFacts = metaboliteFacts;
	}

}
