package edu.uminho.biosynth.core.data.integration.etl.warehouse.components;

// Generated 20-Feb-2014 17:22:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MetaboliteChargeDim generated by hbm2java
 */
@Entity
@Table(name = "metabolite_charge_dim", uniqueConstraints = @UniqueConstraint(columnNames = "charge"))
public class MetaboliteChargeDim implements java.io.Serializable {

	private int id;
	private String charge;
	private Set<MetaboliteFact> metaboliteFacts = new HashSet<MetaboliteFact>(0);

	public MetaboliteChargeDim() {
	}

	public MetaboliteChargeDim(int id) {
		this.id = id;
	}

	public MetaboliteChargeDim(int id, String charge,
			Set<MetaboliteFact> metaboliteFacts) {
		this.id = id;
		this.charge = charge;
		this.metaboliteFacts = metaboliteFacts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "charge", unique = true, length = 10)
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metaboliteChargeDim")
	public Set<MetaboliteFact> getMetaboliteFacts() {
		return this.metaboliteFacts;
	}

	public void setMetaboliteFacts(Set<MetaboliteFact> metaboliteFacts) {
		this.metaboliteFacts = metaboliteFacts;
	}

}
